### ISSUE TITLE
is there a BOM for this?

### ISSUE THREAD

**Issue by wangeris** [quentin-z80/ASM1061#1]
is there a BOM for this?

**Comment by qfreiman** [comment]
The BOM can be found within the kicad project (look at the MFG_PN and DigiKey_PN Fields).

There are 2 main ways you can view it:

1. KiCAD's BOM export tool (which will output a csv file):
[https://docs.kicad.org/6.0/en/eeschema/eeschema.html#bill-of-material-tool](url)
3. The Edit Symbol Fields Tool:
[https://docs.kicad.org/6.0/en/eeschema/eeschema.html#edit-fields-tool](url)
